baseURL: "trialtanikac.github.io/" 
title: Tanika Chakraborty
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: tanikac

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Sponsored Projects
          url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 5     
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am an Associate Professor of Economics at Indian Institute of Management, Calcutta."
    author: Tanika Chakraborty
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tanika Chakraboty
          subtitle: "I am an Associate Professor of Economics at Indian Institute of Management, Calcutta."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Tanika Chakraborty
          buttons:
            - name: Research
              url: /papers/
            - name: Courses
              url: /courses/
            - name: Sponsored Project
              url: /design/
            - name: Newsletter
              url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:pascal.michaillat@gmail.com
        - name: Location
          url: /location/
        - name: Office Hours
          url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=DoOkjXsAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/tanikac?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Tanika Chakraborty"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
